### ISSUE TITLE
Please give ready made Windows Build 32bit and 64bit

### ISSUE THREAD

**Issue by gaamaaresosa** [alexkirsz/dispatch#12]
You guys are doing wonderful job.
But not giving easy solutions to test.
No Windows build given.
Cargo and rustup are not popular every where.

No (Detailed Windows build instructions) on the below link,
https://github.com/alexkirsz/dispatch/pull/10/commits/5400f83321d52fbbc205ccd5d8d80cacfdbdbae6

I have installed and copied Packet.lib
What next and how to build Windows exe ?

EDIT:
After several hours of try I had successfully built the dispatch.exe
"dispatch list" command shows all the VMWare virtual adopters
But the main Ethernet and Cell phone tethered adopters not showing.

Where as old Node.js dispatch-Proxy works great.
Seems some issue in this code.

**Comment by alexkirsz** [comment]
New releases are now automatically built for Windows, macOS, and Linux. You can install from pre-built binaries from the  [Releases](https://github.com/alexkirsz/dispatch/releases) page.

**Comment by gaamaaresosa** [comment]
> New releases are now automatically built for Windows, macOS, and Linux. You can install from pre-built binaries from the [Releases](https://github.com/alexkirsz/dispatch/releases) page.

Thank you so much.
