### ISSUE TITLE
Packet.lib file isn't installed by npcap-1.73.exe

### ISSUE THREAD

**Issue by Nielips** [alexkirsz/dispatch#16]
Hello,

I'm trying to use this tool but when installing Npcap 1.73 file Packet.lib doesn't exist, choosing installation option "Install Npcap in WinPcap API-compatible Mode, the only file I can find that is close is Packet.dll.

Can you provide assistance, sorry if I am making an obvious mistake I don't have much experience with this sort of thing?

**Comment by VictorGarciaOrtega** [comment]
You don't need to install Npcap, just download the SDK... In README below _Installation_ there is an explanation step by step about  Packet.lib

**Comment by alexkirsz** [comment]
With dispatch v0.1.3, it is no longer necessary to install WinPcap in order to build dispatch on Windows. Furthermore, we're now building binaries from Windows, which you can find and install from the [Releases](https://github.com/alexkirsz/dispatch/releases) page.
