### ISSUE TITLE
which packet.lib ?

### ISSUE THREAD

**Issue by vivek2545** [alexkirsz/dispatch#8]
Explain please
Note: you need to install [Npcap](https://npcap.com/#download) and copy the appropriate Packet.lib file from the SDK (x86 or x64) to C:\Users\Username.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib in order to build on Windows.

my errror
linking with `link.exe` failed: exit code: 1181

 note: LINK : fatal error LNK1181: cannot open input file 'Packet.lib'

error: could not compile `dispatch-proxy` due to previous error
error: failed to compile `dispatch-proxy v0.1.0`, intermediate artifacts can be found at `C:\Users\SPELLM~1\AppData\Local\Temp\cargo-installsvnr8I`

**Comment by alexkirsz** [comment]
1. What's your Windows version?
2. Are you running Windows 32-bit or 64-bit?
3. Please share the full path and the contents of the folder where you copied `Packet.lib`.

**Comment by Doimatcuabautroi** [comment]
why dont you release the executable file for easy ? @alexkirsz

**Comment by alexkirsz** [comment]
This is something I intend to do down the road. There are Github actions to automate this process.

**Comment by alexkirsz** [comment]
I've added more detailed Windows instructions in https://github.com/alexkirsz/dispatch/pull/10, which should hopefully resolve @vivek2545's original issue.

I've also created https://github.com/alexkirsz/dispatch/issues/11 to track @Doimatcuabautroi's suggestion to release executable files.
